README_TEMPLATE = """# {project}

## Description

Generated by Forge.
"""

DOCKERFILE_TEMPLATE = """FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

CMD ["python","main.py"]
"""

GITIGNORE_TEMPLATE = """__pycache__/
venv/
.env
*.pyc
.idea/
.vscode/
"""